import migrationConfig from '../db/migrations/migrations';
import journal from '../db/migrations/meta/_journal.json';
import snapshot0002 from '../db/migrations/meta/0002_snapshot.json';
import snapshot0003 from '../db/migrations/meta/0003_snapshot.json';

/**
 * Wayfinder #147 regression guard.
 *
 * drizzle-orm/expo-sqlite/migrator.js (0.45.2) resolves every journal entry via
 * `migrations[`m${idx.toString().padStart(4, '0')}`]`. The config used to export
 * an ARRAY of sql strings, so every lookup returned undefined and migrate()
 * threw "Missing migration: 0000_gorgeous_saracen" on every fresh install,
 * which left the app without any tables (threads/messages/operation_log/...).
 *
 * These tests mirror readMigrationFiles' contract so journal/config corruption
 * fails here in Jest instead of on device.
 */

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

const config = migrationConfig as {
  journal: { entries: JournalEntry[] };
  migrations: Record<string, string>;
};

describe('drizzle migration bundle (#147)', () => {
  it('exposes migrations as an object keyed m0000..mNNNN, not an array', () => {
    expect(Array.isArray(config.migrations)).toBe(false);
    expect(typeof config.migrations).toBe('object');
    expect(config.migrations).not.toBeNull();
    // Arrays would pass the object check above; assert the keyed shape directly.
    for (let i = 0; i < journal.entries.length; i++) {
      const key = `m${String(i).padStart(4, '0')}`;
      expect(Object.prototype.hasOwnProperty.call(config.migrations, key)).toBe(true);
    }
  });

  it('resolves every journal entry to non-empty SQL (readMigrationFiles contract)', () => {
    for (const entry of journal.entries) {
      const query = config.migrations[`m${entry.idx.toString().padStart(4, '0')}`];
      // Mirrors drizzle-orm 0.45.2: `if (!query) throw new Error("Missing migration: ...")`
      expect(query).toBeDefined();
      expect(typeof query).toBe('string');
      expect(query!.trim().length).toBeGreaterThan(0);
      // Migrations generated by drizzle-kit split statements with this marker.
      expect(query).toContain('--> statement-breakpoint');
    }
  });

  it('has unique journal tags', () => {
    const tags = journal.entries.map((e) => e.tag);
    expect(new Set(tags).size).toBe(tags.length);
  });

  it('has journal tags matching the drizzle-kit naming convention', () => {
    for (const entry of journal.entries) {
      expect(entry.tag).toMatch(/^\d{4}_/);
    }
  });

  it('has journal entries sorted by strictly increasing idx starting at 0', () => {
    journal.entries.forEach((entry, i) => {
      expect(entry.idx).toBe(i);
    });
  });

  it('maps each journal tag to its positional migration key (tag digits === idx === m#### key)', () => {
    journal.entries.forEach((entry) => {
      const digits = entry.tag.slice(0, 4);
      expect(Number(digits)).toBe(entry.idx);
      expect(config.migrations[`m${digits}`]).toBeDefined();
    });
  });

  it('keeps the snapshot chain intact: 0003.prevId === 0002.id', () => {
    expect(snapshot0003.prevId).toBe(snapshot0002.id);
  });

  it('uses the sqlite snapshot format drizzle-kit expects', () => {
    expect(snapshot0003.version).toBe('6');
    expect(snapshot0003.dialect).toBe('sqlite');
  });

  it('describes the post-0003 schema (all prior tables plus task execution tables)', () => {
    const tables = Object.keys(snapshot0003.tables);
    for (const expected of [
      'threads',
      'messages',
      'operation_log',
      'tasks',
      'task_runs',
      'task_executions',
      'task_step_executions',
    ]) {
      expect(tables).toContain(expected);
    }
  });
});
